# Data Preparation — CloudTrail Identity Logs

## Step 1: Load Raw CloudTrail Logs

In [41]:
# !pip install pandas

In [42]:
import pandas as pd
import json
import glob
import os

# path to local CloudTrail folder
cloudtrail_folder = os.path.expanduser("~/Downloads/federated-hgnn-anomaly-detection/Dataset/Raw/CloudTrail/CloudTrail/*.json")

records = []

print("Loading CloudTrail logs...")

for file in glob.glob(cloudtrail_folder):
    with open(file, "r") as f:
        data = json.load(f)
        if "Records" in data:
            records.extend(data["Records"])

print("Total raw records:", len(records))

df_identity = pd.DataFrame(records)

df_identity.describe()

Loading CloudTrail logs...
Total raw records: 49068

,eventVersion,userIdentity,eventTime,eventSource,eventName,awsRegion,sourceIPAddress,userAgent,requestParameters,responseElements,requestID,eventID,readOnly,eventType,managementEvent,recipientAccountId,eventCategory,_is_attack,errorCode
count,49068,49068,49068,49068,49068,49068,49068,49068,49068,0,49068,49068,49068,49068,49068,49068,49068,49068,3697
unique,1,49050,47404,11,76,3,25,6,11,0,49068,49068,2,1,1,1,1,2,5
top,1.08,"{'type': 'IAMUser', 'principalId': 'AIDAT5LENE...",2024-03-13T13:08:57Z,logs.amazonaws.com,DescribeLogGroups,us-east-1,10.20.2.25,console.amazonaws.com,{'Host': 'logs.amazonaws.com'},NaN,65338e6a-9754-61a7-c89f-c2bc8e630a65,be655275-856d-c314-cce7-68fb02190eab,True,AwsApiCall,True,123837392027,Management,False,UnauthorizedOperation
freq,49068,2,4,8412,1935,33768,5019,8746,8412,NaN,1,1,33653,49068,49068,49068,49068,47613,781

In [43]:
# Limit to 1000 rows for prototyping
# df_identity = df_identity.head(1000)

print("Shape:", df_identity.shape)

Shape: (49068, 19)

In [44]:
print("Number of records loaded:", len(records))
print()

if len(records) > 0:
    print("Keys in first record:")
    for key in records[0].keys():
        print(" -", key)
else:
    print("Records list is EMPTY — check your CloudTrail folder path")
    print("Folder being searched:", cloudtrail_folder)
    print()
    import glob, os
    files_found = glob.glob(cloudtrail_folder)
    print("JSON files found:", len(files_found))
    for f in files_found:
        print(" -", f)

Number of records loaded: 49068

Keys in first record:
 - eventVersion
 - userIdentity
 - eventTime
 - eventSource
 - eventName
 - awsRegion
 - sourceIPAddress
 - userAgent
 - requestParameters
 - responseElements
 - requestID
 - eventID
 - readOnly
 - eventType
 - managementEvent
 - recipientAccountId
 - eventCategory
 - _is_attack

## Step 2: Initial Inspection

In [45]:
df_identity.info()

<class 'pandas.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   eventVersion        49068 non-null  str
 1   userIdentity        49068 non-null  object
 2   eventTime           49068 non-null  str
 3   eventSource         49068 non-null  str
 4   eventName           49068 non-null  str
 5   awsRegion           49068 non-null  str
 6   sourceIPAddress     49068 non-null  str
 7   userAgent           49068 non-null  str
 8   requestParameters   49068 non-null  object
 9   responseElements    0 non-null      object
 10  requestID           49068 non-null  str
 11  eventID             49068 non-null  str
 12  readOnly            49068 non-null  bool
 13  eventType           49068 non-null  str
 14  managementEvent     49068 non-null  bool
 15  recipientAccountId  49068 non-null  str
 16  eventCategory       49068 non-null  str
 17  _is_attack          49068 non-null  bool
 18  errorCode           3697 non-null   str
dtypes: bool(3), object(3), str(13)
memory usage: 17.0+ MB

In [46]:
df_identity.head()

,eventVersion,userIdentity,eventTime,eventSource,eventName,awsRegion,sourceIPAddress,userAgent,requestParameters,responseElements,requestID,eventID,readOnly,eventType,managementEvent,recipientAccountId,eventCategory,_is_attack,errorCode
0,1.08,"{'type': 'IAMUser', 'principalId': 'AIDAHSADBJ...",2024-03-04T08:01:15Z,s3.amazonaws.com,GetBucketPolicy,us-west-2,192.168.3.113,aws-sdk-go/1.44.261 (go1.19.8; linux; amd64),{'Host': 's3.amazonaws.com'},None,65338e6a-9754-61a7-c89f-c2bc8e630a65,be655275-856d-c314-cce7-68fb02190eab,True,AwsApiCall,True,123837392027,Management,False,NaN
1,1.08,"{'type': 'IAMUser', 'principalId': 'AIDAHSADBJ...",2024-03-04T11:04:44Z,dynamodb.amazonaws.com,PutItem,us-west-2,192.168.3.113,aws-sdk-go/1.44.261 (go1.19.8; linux; amd64),{'Host': 'dynamodb.amazonaws.com'},None,fda90485-10b2-7f06-8d3a-883d97ef44b1,ec30dd29-15d6-818b-bc14-d96eb266a5bd,False,AwsApiCall,True,123837392027,Management,False,NaN
2,1.08,"{'type': 'IAMUser', 'principalId': 'AIDAHSADBJ...",2024-03-04T11:53:51Z,logs.amazonaws.com,CreateLogStream,us-west-2,192.168.3.113,aws-sdk-go/1.44.261 (go1.19.8; linux; amd64),{'Host': 'logs.amazonaws.com'},None,ee8fa831-06dc-e8c9-dcfd-6dbe914aded3,2b77c248-2440-ad41-0d33-da92a04275d3,False,AwsApiCall,True,123837392027,Management,False,NaN
3,1.08,"{'type': 'IAMUser', 'principalId': 'AIDAHSADBJ...",2024-03-04T12:26:15Z,dynamodb.amazonaws.com,PutItem,us-west-2,192.168.3.113,aws-sdk-go/1.44.261 (go1.19.8; linux; amd64),{'Host': 'dynamodb.amazonaws.com'},None,b4c145bd-4fd1-ba31-d61c-d7573515594d,f3246ddb-ed04-9a2a-2a51-88c4a6fd63a6,False,AwsApiCall,True,123837392027,Management,False,NaN
4,1.08,"{'type': 'IAMUser', 'principalId': 'AIDAHSADBJ...",2024-03-04T13:08:10Z,lambda.amazonaws.com,GetFunction,us-west-2,192.168.3.113,aws-sdk-go/1.44.261 (go1.19.8; linux; amd64),{'Host': 'lambda.amazonaws.com'},None,9f8b793f-99e2-9dfa-1d62-acfc11040e10,79017ca5-2a2b-7c36-e7e8-3aafaddfdeae,True,AwsApiCall,True,123837392027,Management,False,NaN

In [47]:
df_identity.tail()

,eventVersion,userIdentity,eventTime,eventSource,eventName,awsRegion,sourceIPAddress,userAgent,requestParameters,responseElements,requestID,eventID,readOnly,eventType,managementEvent,recipientAccountId,eventCategory,_is_attack,errorCode
49063,1.08,"{'type': 'IAMUser', 'principalId': 'AIDAP4YP77...",2024-03-22T14:51:37Z,dynamodb.amazonaws.com,GetItem,eu-west-1,192.168.3.190,Boto3/1.28.3 Python/3.10.12 Linux/5.15.0-76-ge...,{'Host': 'dynamodb.amazonaws.com'},None,360aa572-aa7d-9538-2cba-968957b6715d,86adeadb-ed1d-97d0-c4f6-80f1b92f95af,True,AwsApiCall,True,123837392027,Management,False,NaN
49064,1.08,"{'type': 'IAMUser', 'principalId': 'AIDAP4YP77...",2024-03-22T15:58:22Z,ssm.amazonaws.com,DescribeParameters,eu-west-1,192.168.3.190,Boto3/1.28.3 Python/3.10.12 Linux/5.15.0-76-ge...,{'Host': 'ssm.amazonaws.com'},None,068fd559-9f2e-52cb-45ba-93f640dfff93,75a7880c-753c-5c2f-7a8f-aa49466f3e0c,True,AwsApiCall,True,123837392027,Management,False,NaN
49065,1.08,"{'type': 'IAMUser', 'principalId': 'AIDAP4YP77...",2024-03-22T17:15:32Z,lambda.amazonaws.com,GetFunctionConfiguration,eu-west-1,10.20.1.193,Boto3/1.28.3 Python/3.10.12 Linux/5.15.0-76-ge...,{'Host': 'lambda.amazonaws.com'},None,7a06f6ae-9a57-a279-5fc3-ba7b0888f7e6,e607c6ef-04ab-916c-9f37-23f2cfe4ccc2,True,AwsApiCall,True,123837392027,Management,False,NaN
49066,1.08,"{'type': 'IAMUser', 'principalId': 'AIDAP4YP77...",2024-03-22T19:36:36Z,ssm.amazonaws.com,DescribeParameters,eu-west-1,192.168.3.190,Boto3/1.28.3 Python/3.10.12 Linux/5.15.0-76-ge...,{'Host': 'ssm.amazonaws.com'},None,dfafac11-d762-0530-f2c7-6ba963ed1ae3,90a38517-814b-3dcf-a514-ac2cb30a47bb,True,AwsApiCall,True,123837392027,Management,False,UnauthorizedOperation
49067,1.08,"{'type': 'IAMUser', 'principalId': 'AIDAP4YP77...",2024-03-23T16:26:21Z,lambda.amazonaws.com,InvokeFunction,eu-west-1,192.168.3.190,Boto3/1.28.3 Python/3.10.12 Linux/5.15.0-76-ge...,{'Host': 'lambda.amazonaws.com'},None,85e8f603-a820-110f-df4e-109f8685e461,8f270aa2-c57f-59a5-dc4c-307e85facf0e,False,AwsApiCall,True,123837392027,Management,False,NaN

### Note on Missing Values
High missing % in columns like `errorCode`, `responseElements`, `vpcEndpointId`, and `additionalEventData` is **expected and normal** in CloudTrail.
These fields only appear when a specific event condition is triggered (e.g., `errorCode` only exists if the API call failed).
This is **structurally sparse data by design**, not a data quality problem.

## Step 3: Flatten userIdentity (Nested JSON Column)

In [48]:
# userIdentity is a nested dict — must be flattened before any ML use
user_identity_df = pd.json_normalize(df_identity['userIdentity'])

print("Flattened userIdentity columns:")
print(user_identity_df.columns.tolist())

# Merge flattened columns back into main dataframe
df_identity = pd.concat([df_identity.drop(columns=['userIdentity']), user_identity_df], axis=1)

print("\nNew shape after flattening:", df_identity.shape)

Flattened userIdentity columns:
['type', 'principalId', 'arn', 'accountId', 'accessKeyId', 'userName', 'sessionContext.attributes.creationDate', 'sessionContext.attributes.mfaAuthenticated']

New shape after flattening: (49068, 26)

In [49]:
# Set display options to show everything
pd.set_option('display.max_columns', None)

# Now call your describe or head
print(df_identity.describe(include='all'))

       eventVersion             eventTime         eventSource  \
count         49068                 49068               49068
unique            1                 47404                  11
top            1.08  2024-03-13T13:08:57Z  logs.amazonaws.com
freq          49068                     4                8412

                eventName  awsRegion sourceIPAddress              userAgent  \
count               49068      49068           49068                  49068
unique                 76          3              25                      6
top     DescribeLogGroups  us-east-1      10.20.2.25  console.amazonaws.com
freq                 1935      33768            5019                   8746

                     requestParameters responseElements  \
count                            49068                0
unique                              11                0
top     {'Host': 'logs.amazonaws.com'}              NaN
freq                              8412              NaN

                                   requestID  \
count                                  49068
unique                                 49068
top     65338e6a-9754-61a7-c89f-c2bc8e630a65
freq                                       1

                                     eventID readOnly   eventType  \
count                                  49068    49068       49068
unique                                 49068        2           1
top     be655275-856d-c314-cce7-68fb02190eab     True  AwsApiCall
freq                                       1    33653       49068

       managementEvent recipientAccountId eventCategory _is_attack  \
count            49068              49068         49068      49068
unique               1                  1             1          2
top               True       123837392027    Management      False
freq             49068              49068         49068      47613

                    errorCode     type            principalId  \
count                    3697    49068                  49068
unique                      5        1                    300
top     UnauthorizedOperation  IAMUser  AIDAMUUUZ72EPOQQWNIO3
freq                      781    49068                    500

                                            arn     accountId  \
count                                     49068         49068
unique                                      300             1
top     arn:aws:iam::123837392027:user/user_175  123837392027
freq                                        500         49068

                 accessKeyId  userName sessionContext.attributes.creationDate  \
count                  49068     49068                                  49068
unique                   300       300                                  47404
top     AKIAJA7GTZIKIEEFOQA3  user_175                   2024-03-13T13:08:57Z
freq                     500       500                                      4

       sessionContext.attributes.mfaAuthenticated
count                                       49068
unique                                          2
top                                          true
freq                                        35168

In [50]:
df_identity.info()

<class 'pandas.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 26 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   eventVersion                                49068 non-null  str
 1   eventTime                                   49068 non-null  str
 2   eventSource                                 49068 non-null  str
 3   eventName                                   49068 non-null  str
 4   awsRegion                                   49068 non-null  str
 5   sourceIPAddress                             49068 non-null  str
 6   userAgent                                   49068 non-null  str
 7   requestParameters                           49068 non-null  object
 8   responseElements                            0 non-null      object
 9   requestID                                   49068 non-null  str
 10  eventID                                     49068 non-null  str
 11  readOnly                                    49068 non-null  bool
 12  eventType                                   49068 non-null  str
 13  managementEvent                             49068 non-null  bool
 14  recipientAccountId                          49068 non-null  str
 15  eventCategory                               49068 non-null  str
 16  _is_attack                                  49068 non-null  bool
 17  errorCode                                   3697 non-null   str
 18  type                                        49068 non-null  str
 19  principalId                                 49068 non-null  str
 20  arn                                         49068 non-null  str
 21  accountId                                   49068 non-null  str
 22  accessKeyId                                 49068 non-null  str
 23  userName                                    49068 non-null  str
 24  sessionContext.attributes.creationDate      49068 non-null  str
 25  sessionContext.attributes.mfaAuthenticated  49068 non-null  str
dtypes: bool(3), object(2), str(21)
memory usage: 25.8+ MB

In [51]:
# the number of unique names
unique_user_count = df_identity['userName'].nunique()
print(f"Total Unique Users: {unique_user_count}")

print(df_identity['userName'].value_counts())

# the total number of rows
total_rows = len(df_identity)
print(f"Total Event Logs: {total_rows}")

Total Unique Users: 300
userName
user_175    500
user_224    500
user_099    500
user_131    500
user_183    500
           ...
user_212     60
user_134     60
user_022     60
user_058     60
user_221     60
Name: count, Length: 300, dtype: int64
Total Event Logs: 49068

## Step 4: Handle Missing Values

In [52]:
# Compute missing value report BEFORE any fixes
missing = df_identity.isnull().sum().sort_values(ascending=False)
missing_percent = (missing / len(df_identity)) * 100
missing_table = pd.concat([missing, missing_percent], axis=1)
missing_table.columns = ["Missing Count", "Missing %"]

# Show only columns that actually have missing values
print("Columns with missing values (before fix):")
missing_table[missing_table["Missing Count"] > 0].head(20)

Columns with missing values (before fix):

                  Missing Count   Missing %
responseElements          49068  100.000000
errorCode                 45371   92.465558

In [53]:
# These are the identity columns needed for the HGNN graph nodes and edges.
# Missing here = ambiguous identity = treat as 'Unknown' (preserves the signal).
identity_cols = [
    'type',
    'principalId',
    'accountId',
    'accessKeyId',
    'userName',
    'invokedBy',
    'sessionContext.attributes.mfaAuthenticated',
    'sessionContext.sessionIssuer.type',
    'sessionContext.sessionIssuer.userName'
]

# Only apply fillna to columns that actually exist (safety check)
existing_identity_cols = [c for c in identity_cols if c in df_identity.columns]
df_identity[existing_identity_cols] = df_identity[existing_identity_cols].fillna("Unknown")

# Verify fix was applied
print("Missing values in identity columns AFTER fix:")
print(df_identity[existing_identity_cols].isnull().sum())

Missing values in identity columns AFTER fix:
type                                          0
principalId                                   0
accountId                                     0
accessKeyId                                   0
userName                                      0
sessionContext.attributes.mfaAuthenticated    0
dtype: int64

In [54]:
# For error-related columns, NaN means 'no error occurred' — fill with 'NoError'
error_cols = ['errorCode', 'errorMessage']
for col in error_cols:
    if col in df_identity.columns:
        df_identity[col] = df_identity[col].fillna("NoError")

print("Error columns filled. Sample:")
print(df_identity['errorCode'].value_counts().head())

Error columns filled. Sample:
errorCode
NoError                  45371
UnauthorizedOperation      781
ThrottlingException        780
AccessDenied               727
NoSuchEntity               706
Name: count, dtype: int64

## Step 5: Extract Time Features from eventTime

In [55]:
df_identity['eventTime'] = pd.to_datetime(df_identity['eventTime'], utc=True)

df_identity['event_hour']      = df_identity['eventTime'].dt.hour
df_identity['event_dayofweek'] = df_identity['eventTime'].dt.dayofweek
df_identity['event_date']      = df_identity['eventTime'].dt.date
df_identity['is_weekend']      = df_identity['event_dayofweek'].isin([5, 6]).astype(int)

# is_off_hours: access outside 08:00-18:00 = potential anomaly signal
df_identity['is_off_hours'] = (~df_identity['event_hour'].between(8, 18)).astype(int)

print("Time features added.")
df_identity[['eventTime', 'event_hour', 'event_dayofweek', 'is_weekend', 'is_off_hours']].head()

Time features added.

,eventTime,event_hour,event_dayofweek,is_weekend,is_off_hours
0,2024-03-04 08:01:15+00:00,8,0,0,0
1,2024-03-04 11:04:44+00:00,11,0,0,0
2,2024-03-04 11:53:51+00:00,11,0,0,0
3,2024-03-04 12:26:15+00:00,12,0,0,0
4,2024-03-04 13:08:10+00:00,13,0,0,0

In [56]:
df_identity[['eventTime', 'event_hour', 'event_dayofweek', 'is_weekend', 'is_off_hours']].describe()

         event_hour  event_dayofweek    is_weekend  is_off_hours
count  49068.000000     49068.000000  49068.000000  49068.000000
mean      12.401280         2.162448      0.045304      0.124419
std        3.703908         1.563684      0.207973      0.330063
min        0.000000         0.000000      0.000000      0.000000
25%       10.000000         1.000000      0.000000      0.000000
50%       13.000000         2.000000      0.000000      0.000000
75%       15.000000         3.000000      0.000000      0.000000
max       23.000000         6.000000      1.000000      1.000000

## Step 6: Attach Ground-Truth Anomaly Labels
Labels come from the dataset's own `labels.json` manifest, which records which
accounts were compromised and in which window.

This replaces the earlier rule-based heuristic (`eventName in HIGH_RISK_EVENTS`).
That rule was circular: it derived the label from `eventName`, the same column the
feature `unique_events` is built from, so the model was partly reading its own
answer key. Ground truth from the manifest is independent of every input feature.

In [57]:
LABELS_PATH = os.path.expanduser(
    "~/Downloads/federated-hgnn-anomaly-detection/Dataset/Raw/CloudTrail/CloudTrail/labels.json")

# Ground truth must never be derived from a rule over eventName: that column also
# feeds the unique_events feature, so such a label would leak into the inputs.
# Preferred source is the dataset's own manifest; datasets that predate it encode
# the class in the account name instead.
scenarios = pd.Series(dtype=int)

if os.path.exists(LABELS_PATH):
    with open(LABELS_PATH) as f:
        entities = json.load(f)["entities"]
    user_labels = {e["user"]: e["label"] for e in entities}
    scenarios = pd.Series([e["scenario"] for e in entities if e.get("scenario")]).value_counts()
    label_source = "labels.json manifest"
else:
    users = df_identity["userName"].dropna().unique()
    user_labels = {u: int("hacker" in str(u).lower()) for u in users}
    label_source = "account-name convention (no labels.json found)"

df_identity["is_anomaly"] = df_identity["userName"].map(user_labels).fillna(0).astype(int)

n_users = df_identity["userName"].nunique()
n_anom_users = df_identity.loc[df_identity.is_anomaly == 1, "userName"].nunique()

print(f"Label source: {label_source}")
print(f"  compromised accounts : {n_anom_users} / {n_users} ({n_anom_users / n_users:.1%})")

unmapped = set(df_identity["userName"].dropna().unique()) - set(user_labels)
if unmapped:
    print(f"  WARNING: {len(unmapped)} accounts absent from the label source, "
          f"defaulted to normal: {sorted(unmapped)[:5]}")
if n_anom_users == 0:
    raise ValueError(
        "No anomalous accounts found. The label source does not match this dataset "
        "(e.g. a labels.json left over from a different generation). Fix before continuing."
    )

print()
print("Event-level label distribution (every event of a compromised account is flagged):")
print(df_identity["is_anomaly"].value_counts())
if not scenarios.empty:
    print("\nAttack scenarios present:")
    print(scenarios.to_string())

Label source: labels.json manifest
  compromised accounts : 45 / 300 (15.0%)

Event-level label distribution (every event of a compromised account is flagged):
is_anomaly
0    41320
1     7748
Name: count, dtype: int64

Attack scenarios present:
privilege_escalation    14
credential_access       12
persistence             11
data_exfiltration        8

## Step 7: Select Final Columns for HGNN Graph Construction
These columns map directly to the graph schema defined in the thesis methodology:
- **Nodes**: `userName` (identity), `sourceIPAddress` (network bridge), `eventSource` (target service)
- **Edges**: defined by `eventName` (what action was taken)
- **Features**: time features, MFA status, error status
- **Label**: `is_anomaly`

In [58]:
FINAL_COLS = [
    # --- GRAPH NODES (The Skeleton) ---
    'userName',         # Will become 'user' nodes
    'sourceIPAddress',  # Will become 'ip' nodes
    'eventSource',      # Will become 'service' nodes
    
    # --- NODE FEATURES (The Intelligence) ---
    'eventName',        # Crucial: distinguishes specific actions
    'readOnly',         # Distinguishes 'Discovery' from 'Modification'
    'errorCode',        # Critical: the #1 indicator of an attack
    
    # --- IDENTITY CONTEXT ---
    'type',             # Distinguishes IAMUser vs AssumedRole
    'sessionContext.attributes.mfaAuthenticated', # Security posture check
    
    # --- TARGET LABEL ---
    'is_anomaly'        # Your fixed ground truth
]

# Only keep columns that exist in the dataframe
final_cols_existing = [c for c in FINAL_COLS if c in df_identity.columns]
df_final = df_identity[final_cols_existing].copy()

print("Final dataframe shape:", df_final.shape)
print("\nRemaining missing values:")
print(df_final.isnull().sum()[df_final.isnull().sum() > 0])

df_final.head()

Final dataframe shape: (49068, 9)

Remaining missing values:
Series([], dtype: int64)

,userName,sourceIPAddress,eventSource,eventName,readOnly,errorCode,type,sessionContext.attributes.mfaAuthenticated,is_anomaly
0,user_094,192.168.3.113,s3.amazonaws.com,GetBucketPolicy,True,NoError,IAMUser,true,0
1,user_094,192.168.3.113,dynamodb.amazonaws.com,PutItem,False,NoError,IAMUser,true,0
2,user_094,192.168.3.113,logs.amazonaws.com,CreateLogStream,False,NoError,IAMUser,true,0
3,user_094,192.168.3.113,dynamodb.amazonaws.com,PutItem,False,NoError,IAMUser,true,0
4,user_094,192.168.3.113,lambda.amazonaws.com,GetFunction,True,NoError,IAMUser,true,0

In [59]:
df_final.isnull().sum()

userName                                      0
sourceIPAddress                               0
eventSource                                   0
eventName                                     0
readOnly                                      0
errorCode                                     0
type                                          0
sessionContext.attributes.mfaAuthenticated    0
is_anomaly                                    0
dtype: int64

In [60]:
# Save the cleaned dataframe for the next stage (Graph Construction)
output_path = os.path.expanduser("~/Downloads/federated-hgnn-anomaly-detection/Dataset/Processed/df_identity_clean.csv")
df_final.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print("Data preparation complete. Ready for graph construction.")

Saved to: /Users/philberttan/Downloads/federated-hgnn-anomaly-detection/Dataset/Processed/df_identity_clean.csv
Data preparation complete. Ready for graph construction.