# Data Preparation — CloudTrail Identity Logs

## Step 1: Load Raw CloudTrail Logs

In [1]:
# !pip install pandas

In [ ]:
import pandas as pd
import json
import glob
import os

# path to local CloudTrail folder
cloudtrail_folder = os.path.expanduser("~/Downloads/federated-hgnn-anomaly-detection/Dataset/Raw/CloudTrail/CloudTrail/*.json")

records = []

print("Loading CloudTrail logs...")

for file in glob.glob(cloudtrail_folder):
    with open(file, "r") as f:
        data = json.load(f)
        if "Records" in data:
            records.extend(data["Records"])

print("Total raw records:", len(records))

df_identity = pd.DataFrame(records)

df_identity.describe()

Loading CloudTrail logs...
Total raw records: 19117

,eventVersion,userIdentity,eventTime,eventSource,eventName,awsRegion,sourceIPAddress,userAgent,requestParameters,responseElements,...,eventCategory,resources,vpcEndpointId,tlsDetails,errorCode,errorMessage,apiVersion,sessionCredentialFromConsole,sharedEventID,serviceEventDetails
count,19117,19117,19117,19117,19117,19117,19117,19117,17169,1646,...,19117,5708,2141,15059,1953,1931,124,2264,36,2
unique,2,1416,595,29,260,1,71,155,1250,263,...,1,79,5,38,32,95,4,1,36,1
top,1.08,"{'type': 'IAMUser', 'principalId': 'AIDATFQR7N...",2023-07-10T11:42:44Z,ec2.amazonaws.com,DescribeEventAggregates,us-east-1,10.10.10.4,APN/1.0 HashiCorp/1.0 Terraform/1.1.2 (+https:...,"{'accountAttributeNameSet': {}, 'filterSet': {}}","{'version': 1, 'tier': 'Standard'}",...,Management,"[{'accountId': '123837392027', 'type': 'AWS::K...",vpce-f40dc59d,"{'tlsVersion': 'TLSv1.2', 'cipherSuite': 'ECDH...",ThrottlingException,Rate exceeded,2013-04-01,true,71797d26-1286-4204-81d4-cbcce8819672,{'snapshotId': 'snap-0e83092ae538da583'}
freq,18934,2104,1429,4624,1133,19117,2238,4205,204,223,...,19117,897,1713,4080,561,561,81,2264,1,2

In [3]:
# Limit to 1000 rows for prototyping
# df_identity = df_identity.head(1000)

print("Shape:", df_identity.shape)

Shape: (19117, 27)

In [4]:
print("Number of records loaded:", len(records))
print()

if len(records) > 0:
    print("Keys in first record:")
    for key in records[0].keys():
        print(" -", key)
else:
    print("Records list is EMPTY — check your CloudTrail folder path")
    print("Folder being searched:", cloudtrail_folder)
    print()
    import glob, os
    files_found = glob.glob(cloudtrail_folder)
    print("JSON files found:", len(files_found))
    for f in files_found:
        print(" -", f)

Number of records loaded: 19117

Keys in first record:
 - eventVersion
 - userIdentity
 - eventTime
 - eventSource
 - eventName
 - awsRegion
 - sourceIPAddress
 - userAgent
 - requestParameters
 - responseElements
 - additionalEventData
 - requestID
 - eventID
 - readOnly
 - eventType
 - managementEvent
 - recipientAccountId
 - eventCategory

## Step 2: Initial Inspection

In [5]:
df_identity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19117 entries, 0 to 19116
Data columns (total 27 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   eventVersion                  19117 non-null  object
 1   userIdentity                  19117 non-null  object
 2   eventTime                     19117 non-null  object
 3   eventSource                   19117 non-null  object
 4   eventName                     19117 non-null  object
 5   awsRegion                     19117 non-null  object
 6   sourceIPAddress               19117 non-null  object
 7   userAgent                     19117 non-null  object
 8   requestParameters             17169 non-null  object
 9   responseElements              1646 non-null   object
 10  additionalEventData           4066 non-null   object
 11  requestID                     19103 non-null  object
 12  eventID                       19117 non-null  object
 13  readOnly                      19117 non-null  bool
 14  eventType                     19117 non-null  object
 15  managementEvent               19117 non-null  bool
 16  recipientAccountId            19117 non-null  object
 17  eventCategory                 19117 non-null  object
 18  resources                     5708 non-null   object
 19  vpcEndpointId                 2141 non-null   object
 20  tlsDetails                    15059 non-null  object
 21  errorCode                     1953 non-null   object
 22  errorMessage                  1931 non-null   object
 23  apiVersion                    124 non-null    object
 24  sessionCredentialFromConsole  2264 non-null   object
 25  sharedEventID                 36 non-null     object
 26  serviceEventDetails           2 non-null      object
dtypes: bool(2), object(25)
memory usage: 3.7+ MB

In [6]:
df_identity.head()

,eventVersion,userIdentity,eventTime,eventSource,eventName,awsRegion,sourceIPAddress,userAgent,requestParameters,responseElements,...,eventCategory,resources,vpcEndpointId,tlsDetails,errorCode,errorMessage,apiVersion,sessionCredentialFromConsole,sharedEventID,serviceEventDetails
0,1.08,"{'type': 'IAMUser', 'principalId': 'AIDATFQR7N...",2023-07-10T11:42:36Z,s3.amazonaws.com,GetStorageLensConfiguration,us-east-1,AWS Internal,AWS Internal,{'Host': '123837392027.s3-control.us-east-1.am...,None,...,Management,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.08,"{'type': 'IAMUser', 'principalId': 'AIDATFQR7N...",2023-07-10T11:42:44Z,s3.amazonaws.com,GetBucketPublicAccessBlock,us-east-1,10.248.16.43,"[S3Console/0.4, aws-internal/3 aws-sdk-java/1....","{'publicAccessBlock': '', 'bucketName': 'baker...",None,...,Management,"[{'accountId': '123837392027', 'type': 'AWS::S...",vpce-f40dc59d,"{'tlsVersion': 'TLSv1.2', 'cipherSuite': 'ECDH...",NaN,NaN,NaN,NaN,NaN,NaN
2,1.08,"{'type': 'IAMUser', 'principalId': 'AIDATFQR7N...",2023-07-10T11:42:44Z,s3.amazonaws.com,GetBucketPolicyStatus,us-east-1,10.248.16.43,"[S3Console/0.4, aws-internal/3 aws-sdk-java/1....",{'bucketName': 'baker221b-bucketssecuritylogsb...,None,...,Management,"[{'accountId': '123837392027', 'type': 'AWS::S...",vpce-f40dc59d,"{'tlsVersion': 'TLSv1.2', 'cipherSuite': 'ECDH...",NaN,NaN,NaN,NaN,NaN,NaN
3,1.08,"{'type': 'IAMUser', 'principalId': 'AIDATFQR7N...",2023-07-10T11:42:44Z,s3.amazonaws.com,GetBucketAcl,us-east-1,10.248.16.43,"[S3Console/0.4, aws-internal/3 aws-sdk-java/1....",{'bucketName': 'baker221b-bucketssecuritylogsb...,None,...,Management,"[{'accountId': '123837392027', 'type': 'AWS::S...",vpce-f40dc59d,"{'tlsVersion': 'TLSv1.2', 'cipherSuite': 'ECDH...",NaN,NaN,NaN,NaN,NaN,NaN
4,1.08,"{'type': 'IAMUser', 'principalId': 'AIDATFQR7N...",2023-07-10T11:42:44Z,s3.amazonaws.com,GetBucketPublicAccessBlock,us-east-1,10.248.16.43,"[S3Console/0.4, aws-internal/3 aws-sdk-java/1....","{'publicAccessBlock': '', 'bucketName': 'invic...",None,...,Management,"[{'accountId': '123837392027', 'type': 'AWS::S...",vpce-f40dc59d,"{'tlsVersion': 'TLSv1.2', 'cipherSuite': 'ECDH...",NoSuchPublicAccessBlockConfiguration,The public access block configuration was not ...,NaN,NaN,NaN,NaN

In [7]:
df_identity.tail()

,eventVersion,userIdentity,eventTime,eventSource,eventName,awsRegion,sourceIPAddress,userAgent,requestParameters,responseElements,...,eventCategory,resources,vpcEndpointId,tlsDetails,errorCode,errorMessage,apiVersion,sessionCredentialFromConsole,sharedEventID,serviceEventDetails
19112,1.08,"{'type': 'IAMUser', 'principalId': 'AIDATFQR7N...",2023-07-10T12:27:43Z,account.amazonaws.com,GetRegionOptStatus,us-east-1,192.168.1.50,Boto3/1.26.165 Python/3.10.6 Linux/5.19.0-46-g...,{'RegionName': 'eu-north-1'},None,...,Management,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19113,1.08,"{'type': 'IAMUser', 'principalId': 'AIDATFQR7N...",2023-07-10T12:27:45Z,route53.amazonaws.com,ListHostedZones,us-east-1,192.168.1.50,Boto3/1.26.165 Python/3.10.6 Linux/5.19.0-46-g...,None,None,...,Management,NaN,NaN,"{'tlsVersion': 'TLSv1.2', 'cipherSuite': 'ECDH...",NaN,NaN,2013-04-01,NaN,NaN,NaN
19114,1.08,"{'type': 'IAMUser', 'principalId': 'AIDATFQR7N...",2023-07-10T12:32:49Z,health.amazonaws.com,DescribeEventAggregates,us-east-1,192.168.1.50,AWS Internal,"{'filter': {'startTimes': [{'from': 'Jul 3, 20...",None,...,Management,NaN,NaN,NaN,NaN,NaN,NaN,true,NaN,NaN
19115,1.08,"{'type': 'IAMUser', 'principalId': 'AIDATFQR7N...",2023-07-10T12:32:49Z,health.amazonaws.com,DescribeEventAggregates,us-east-1,192.168.1.50,AWS Internal,"{'aggregateField': 'eventTypeCategory', 'filte...",None,...,Management,NaN,NaN,NaN,NaN,NaN,NaN,true,NaN,NaN
19116,1.08,"{'type': 'IAMUser', 'principalId': 'AIDATFQR7N...",2023-07-10T12:37:50Z,health.amazonaws.com,DescribeEventAggregates,us-east-1,192.168.1.50,AWS Internal,"{'filter': {'startTimes': [{'from': 'Jul 3, 20...",None,...,Management,NaN,NaN,NaN,NaN,NaN,NaN,true,NaN,NaN

### Note on Missing Values
High missing % in columns like `errorCode`, `responseElements`, `vpcEndpointId`, and `additionalEventData` is **expected and normal** in CloudTrail.
These fields only appear when a specific event condition is triggered (e.g., `errorCode` only exists if the API call failed).
This is **structurally sparse data by design**, not a data quality problem.

## Step 3: Flatten userIdentity (Nested JSON Column)

In [8]:
# userIdentity is a nested dict — must be flattened before any ML use
user_identity_df = pd.json_normalize(df_identity['userIdentity'])

print("Flattened userIdentity columns:")
print(user_identity_df.columns.tolist())

# Merge flattened columns back into main dataframe
df_identity = pd.concat([df_identity.drop(columns=['userIdentity']), user_identity_df], axis=1)

print("\nNew shape after flattening:", df_identity.shape)

Flattened userIdentity columns:
['type', 'principalId', 'arn', 'accountId', 'accessKeyId', 'userName', 'invokedBy', 'sessionContext.attributes.creationDate', 'sessionContext.attributes.mfaAuthenticated', 'sessionContext.sessionIssuer.type', 'sessionContext.sessionIssuer.principalId', 'sessionContext.sessionIssuer.arn', 'sessionContext.sessionIssuer.accountId', 'sessionContext.sessionIssuer.userName', 'sessionContext.ec2RoleDelivery']

New shape after flattening: (19117, 41)

In [9]:
# Set display options to show everything
pd.set_option('display.max_columns', None)

# Now call your describe or head
print(df_identity.describe(include='all'))

       eventVersion             eventTime        eventSource  \
count         19117                 19117              19117
unique            2                   595                 29
top            1.08  2023-07-10T11:42:44Z  ec2.amazonaws.com
freq          18934                  1429               4624

                      eventName  awsRegion sourceIPAddress  \
count                     19117      19117           19117
unique                      260          1              71
top     DescribeEventAggregates  us-east-1      10.10.10.4
freq                       1133      19117            2238

                                                userAgent  \
count                                               19117
unique                                                155
top     APN/1.0 HashiCorp/1.0 Terraform/1.1.2 (+https:...
freq                                                 4205

                                       requestParameters  \
count                                              17169
unique                                              1250
top     {'accountAttributeNameSet': {}, 'filterSet': {}}
freq                                                 204

                          responseElements  \
count                                 1646
unique                                 263
top     {'version': 1, 'tier': 'Standard'}
freq                                   223

                                      additionalEventData  \
count                                                4066
unique                                                290
top     {'SignatureVersion': 'SigV4', 'CipherSuite': '...
freq                                                   48

                                   requestID  \
count                                  19103
unique                                  2848
top     9525f598-d01f-472a-9dbd-7e3cd6f9d433
freq                                      92

                                     eventID readOnly   eventType  \
count                                  19117    19117       19117
unique                                  2900        2           3
top     717a8dbf-9758-4805-9e97-bee88605bad5     True  AwsApiCall
freq                                      48    16288       19063

       managementEvent recipientAccountId eventCategory  \
count            19117              19117         19117
unique               1                  1             1
top               True       123837392027    Management
freq             19117              19117         19117

                                                resources  vpcEndpointId  \
count                                                5708           2141
unique                                                 79              5
top     [{'accountId': '123837392027', 'type': 'AWS::K...  vpce-f40dc59d
freq                                                  897           1713

                                               tlsDetails  \
count                                               15059
unique                                                 38
top     {'tlsVersion': 'TLSv1.2', 'cipherSuite': 'ECDH...
freq                                                 4080

                  errorCode   errorMessage  apiVersion  \
count                  1953           1931         124
unique                   32             95           4
top     ThrottlingException  Rate exceeded  2013-04-01
freq                    561            561          81

       sessionCredentialFromConsole                         sharedEventID  \
count                          2264                                    36
unique                            1                                    36
top                            true  71797d26-1286-4204-81d4-cbcce8819672
freq                           2264                                     1

                             serviceEventDetails     type  \
count                                          2    19075
unique                                         1        3
top     {'snapshotId': 'snap-0e83092ae538da583'}  IAMUser
freq                                           2    18965

                  principalId                                      arn  \
count                   19041                                    19036
unique                     13                                       68
top     AIDATFQR7NSC5AU2ZV3IE  arn:aws:iam::123837392027:user/bert-jan
freq                    14408                                     2641

           accountId           accessKeyId  userName     invokedBy  \
count          19083                 19028     18965          2128
unique             1                   134        58             9
top     123837392027  AKIATFQR7NSC8Q4X20BJ  bert-jan  AWS Internal
freq           19083                 11460      2642          1035

       sessionContext.attributes.creationDate  \
count                                    5683
unique                                     24
top                      2023-07-10T11:42:31Z
freq                                     2670

       sessionContext.attributes.mfaAuthenticated  \
count                                        5683
unique                                          2
top                                          true
freq                                         4296

       sessionContext.sessionIssuer.type  \
count                                 76
unique                                 1
top                                 Role
freq                                  76

       sessionContext.sessionIssuer.principalId  \
count                                        76
unique                                        9
top                       AROATFQR7NSCWWVLB7BES
freq                                         29

                         sessionContext.sessionIssuer.arn  \
count                                                  76
unique                                                  9
top     arn:aws:iam::123837392027:role/stratus-red-tea...
freq                                                   29

       sessionContext.sessionIssuer.accountId  \
count                                      76
unique                                      1
top                              123837392027
freq                                       76

              sessionContext.sessionIssuer.userName  \
count                                            76
unique                                            9
top     stratus-red-team-ec2-get-password-data-role
freq                                             29

       sessionContext.ec2RoleDelivery
count                              23
unique                              2
top                               2.0
freq                               21

In [10]:
df_identity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19117 entries, 0 to 19116
Data columns (total 41 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   eventVersion                                19117 non-null  object
 1   eventTime                                   19117 non-null  object
 2   eventSource                                 19117 non-null  object
 3   eventName                                   19117 non-null  object
 4   awsRegion                                   19117 non-null  object
 5   sourceIPAddress                             19117 non-null  object
 6   userAgent                                   19117 non-null  object
 7   requestParameters                           17169 non-null  object
 8   responseElements                            1646 non-null   object
 9   additionalEventData                         4066 non-null   object
 10  requestID                                   19103 non-null  object
 11  eventID                                     19117 non-null  object
 12  readOnly                                    19117 non-null  bool
 13  eventType                                   19117 non-null  object
 14  managementEvent                             19117 non-null  bool
 15  recipientAccountId                          19117 non-null  object
 16  eventCategory                               19117 non-null  object
 17  resources                                   5708 non-null   object
 18  vpcEndpointId                               2141 non-null   object
 19  tlsDetails                                  15059 non-null  object
 20  errorCode                                   1953 non-null   object
 21  errorMessage                                1931 non-null   object
 22  apiVersion                                  124 non-null    object
 23  sessionCredentialFromConsole                2264 non-null   object
 24  sharedEventID                               36 non-null     object
 25  serviceEventDetails                         2 non-null      object
 26  type                                        19075 non-null  object
 27  principalId                                 19041 non-null  object
 28  arn                                         19036 non-null  object
 29  accountId                                   19083 non-null  object
 30  accessKeyId                                 19028 non-null  object
 31  userName                                    18965 non-null  object
 32  invokedBy                                   2128 non-null   object
 33  sessionContext.attributes.creationDate      5683 non-null   object
 34  sessionContext.attributes.mfaAuthenticated  5683 non-null   object
 35  sessionContext.sessionIssuer.type           76 non-null     object
 36  sessionContext.sessionIssuer.principalId    76 non-null     object
 37  sessionContext.sessionIssuer.arn            76 non-null     object
 38  sessionContext.sessionIssuer.accountId      76 non-null     object
 39  sessionContext.sessionIssuer.userName       76 non-null     object
 40  sessionContext.ec2RoleDelivery              23 non-null     object
dtypes: bool(2), object(39)
memory usage: 5.7+ MB

In [11]:
# the number of unique names
unique_user_count = df_identity['userName'].nunique()
print(f"Total Unique Users: {unique_user_count}")

print(df_identity['userName'].value_counts())

# the total number of rows
total_rows = len(df_identity)
print(f"Total Event Logs: {total_rows}")

Total Unique Users: 58
userName
bert-jan                              2642
hacker_user_04                        2390
hacker_user_02                        2375
hacker_user_03                        2357
hacker_user_05                        2355
hacker_user_01                        2289
benjamin                               105
normal_user_11                         105
normal_user_38                         104
normal_user_24                         103
normal_user_46                         103
normal_user_26                         102
normal_user_41                         102
normal_user_42                         102
normal_user_15                         102
normal_user_30                         102
normal_user_17                         101
normal_user_08                         100
normal_user_22                         100
normal_user_13                          97
normal_user_44                          97
normal_user_47                          97
normal_user_32                          96
normal_user_27                          96
normal_user_10                          95
normal_user_04                          95
normal_user_19                          95
normal_user_45                          94
normal_user_03                          93
normal_user_09                          93
normal_user_49                          90
normal_user_36                          89
normal_user_39                          88
normal_user_18                          88
normal_user_37                          87
normal_user_14                          86
normal_user_20                          86
normal_user_50                          84
normal_user_05                          84
normal_user_12                          84
normal_user_02                          83
normal_user_25                          82
normal_user_29                          81
normal_user_07                          80
normal_user_23                          80
normal_user_28                          80
normal_user_31                          78
normal_user_21                          78
normal_user_01                          77
normal_user_06                          77
normal_user_16                          76
normal_user_40                          75
normal_user_35                          75
normal_user_43                          74
normal_user_48                          74
normal_user_33                          73
normal_user_34                          68
stratus-red-team-nmfalu-gfjyeaypjt       1
Name: count, dtype: int64
Total Event Logs: 19117

## Step 4: Handle Missing Values

In [12]:
# Compute missing value report BEFORE any fixes
missing = df_identity.isnull().sum().sort_values(ascending=False)
missing_percent = (missing / len(df_identity)) * 100
missing_table = pd.concat([missing, missing_percent], axis=1)
missing_table.columns = ["Missing Count", "Missing %"]

# Show only columns that actually have missing values
print("Columns with missing values (before fix):")
missing_table[missing_table["Missing Count"] > 0].head(20)

Columns with missing values (before fix):

                                            Missing Count  Missing %
serviceEventDetails                                 19115  99.989538
sessionContext.ec2RoleDelivery                      19094  99.879688
sharedEventID                                       19081  99.811686
sessionContext.sessionIssuer.type                   19041  99.602448
sessionContext.sessionIssuer.arn                    19041  99.602448
sessionContext.sessionIssuer.principalId            19041  99.602448
sessionContext.sessionIssuer.accountId              19041  99.602448
sessionContext.sessionIssuer.userName               19041  99.602448
apiVersion                                          18993  99.351363
responseElements                                    17471  91.389862
errorMessage                                        17186  89.899043
errorCode                                           17164  89.783962
invokedBy                                           16989  88.868546
vpcEndpointId                                       16976  88.800544
sessionCredentialFromConsole                        16853  88.157138
additionalEventData                                 15051  78.730972
sessionContext.attributes.creationDate              13434  70.272532
sessionContext.attributes.mfaAuthenticated          13434  70.272532
resources                                           13409  70.141759
tlsDetails                                           4058  21.227180

In [13]:
# These are the identity columns needed for the HGNN graph nodes and edges.
# Missing here = ambiguous identity = treat as 'Unknown' (preserves the signal).
identity_cols = [
    'type',
    'principalId',
    'accountId',
    'accessKeyId',
    'userName',
    'invokedBy',
    'sessionContext.attributes.mfaAuthenticated',
    'sessionContext.sessionIssuer.type',
    'sessionContext.sessionIssuer.userName'
]

# Only apply fillna to columns that actually exist (safety check)
existing_identity_cols = [c for c in identity_cols if c in df_identity.columns]
df_identity[existing_identity_cols] = df_identity[existing_identity_cols].fillna("Unknown")

# Verify fix was applied
print("Missing values in identity columns AFTER fix:")
print(df_identity[existing_identity_cols].isnull().sum())

Missing values in identity columns AFTER fix:
type                                          0
principalId                                   0
accountId                                     0
accessKeyId                                   0
userName                                      0
invokedBy                                     0
sessionContext.attributes.mfaAuthenticated    0
sessionContext.sessionIssuer.type             0
sessionContext.sessionIssuer.userName         0
dtype: int64

In [14]:
# For error-related columns, NaN means 'no error occurred' — fill with 'NoError'
error_cols = ['errorCode', 'errorMessage']
for col in error_cols:
    if col in df_identity.columns:
        df_identity[col] = df_identity[col].fillna("NoError")

print("Error columns filled. Sample:")
print(df_identity['errorCode'].value_counts().head())

Error columns filled. Sample:
errorCode
NoError                                 17164
ThrottlingException                       561
NoSuchBucketPolicy                        381
NoSuchPublicAccessBlockConfiguration      296
AccessDenied                               79
Name: count, dtype: int64

## Step 5: Extract Time Features from eventTime

In [15]:
df_identity['eventTime'] = pd.to_datetime(df_identity['eventTime'], utc=True)

df_identity['event_hour']      = df_identity['eventTime'].dt.hour
df_identity['event_dayofweek'] = df_identity['eventTime'].dt.dayofweek
df_identity['event_date']      = df_identity['eventTime'].dt.date
df_identity['is_weekend']      = df_identity['event_dayofweek'].isin([5, 6]).astype(int)

# is_off_hours: access outside 08:00-18:00 = potential anomaly signal
df_identity['is_off_hours'] = (~df_identity['event_hour'].between(8, 18)).astype(int)

print("Time features added.")
df_identity[['eventTime', 'event_hour', 'event_dayofweek', 'is_weekend', 'is_off_hours']].head()

Time features added.

,eventTime,event_hour,event_dayofweek,is_weekend,is_off_hours
0,2023-07-10 11:42:36+00:00,11,0,0,0
1,2023-07-10 11:42:44+00:00,11,0,0,0
2,2023-07-10 11:42:44+00:00,11,0,0,0
3,2023-07-10 11:42:44+00:00,11,0,0,0
4,2023-07-10 11:42:44+00:00,11,0,0,0

In [16]:
df_identity[['eventTime', 'event_hour', 'event_dayofweek', 'is_weekend', 'is_off_hours']].describe()

         event_hour  event_dayofweek  is_weekend  is_off_hours
count  19117.000000          19117.0     19117.0       19117.0
mean      11.613799              0.0         0.0           0.0
std        0.486890              0.0         0.0           0.0
min       11.000000              0.0         0.0           0.0
25%       11.000000              0.0         0.0           0.0
50%       12.000000              0.0         0.0           0.0
75%       12.000000              0.0         0.0           0.0
max       12.000000              0.0         0.0           0.0

## Step 6: Create Anomaly Labels
This is a **rule-based heuristic label** for prototype purposes.
An event is flagged as anomalous if it matches known attacker patterns in the Invictus-IR dataset.

In [17]:
# Source: Invictus-IR attack scenario documentation
HIGH_RISK_EVENTS = [
    'AssumeRole',
    'CreateAccessKey',
    'AttachUserPolicy',
    'AttachRolePolicy',
    'PutUserPolicy',
    'CreateLoginProfile',
    'UpdateLoginProfile',
    'GetSecretValue',
    'ListBuckets',
    'GetObject',
]

# Rule: flag as anomaly if high-risk event AND (off-hours OR no MFA OR there is an errorCode that is not NoError)
is_high_risk_event = df_identity['eventName'].isin(HIGH_RISK_EVENTS)
is_no_mfa = df_identity.get('sessionContext.attributes.mfaAuthenticated', pd.Series(['Unknown']*len(df_identity))) != 'true'
is_failed = (df_identity['errorCode'] != 'NoError') & (df_identity['errorCode'].notnull())

df_identity['is_anomaly'] = (
    is_high_risk_event & (is_no_mfa | is_failed)
).astype(int)

print("Label distribution:")
print(df_identity['is_anomaly'].value_counts())
print(f"\nAnomaly rate: {df_identity['is_anomaly'].mean():.2%}")

Label distribution:
is_anomaly
0    18587
1      530
Name: count, dtype: int64

Anomaly rate: 2.77%

## Step 7: Select Final Columns for HGNN Graph Construction
These columns map directly to the graph schema defined in the thesis methodology:
- **Nodes**: `userName` (identity), `sourceIPAddress` (network bridge), `eventSource` (target service)
- **Edges**: defined by `eventName` (what action was taken)
- **Features**: time features, MFA status, error status
- **Label**: `is_anomaly`

In [18]:
FINAL_COLS = [
    # --- GRAPH NODES (The Skeleton) ---
    'userName',         # Will become 'user' nodes
    'sourceIPAddress',  # Will become 'ip' nodes
    'eventSource',      # Will become 'service' nodes
    
    # --- NODE FEATURES (The Intelligence) ---
    'eventName',        # Crucial: distinguishes specific actions
    'readOnly',         # Distinguishes 'Discovery' from 'Modification'
    'errorCode',        # Critical: the #1 indicator of an attack
    
    # --- IDENTITY CONTEXT ---
    'type',             # Distinguishes IAMUser vs AssumedRole
    'sessionContext.attributes.mfaAuthenticated', # Security posture check
    
    # --- TARGET LABEL ---
    'is_anomaly'        # Your fixed ground truth
]

# Only keep columns that exist in the dataframe
final_cols_existing = [c for c in FINAL_COLS if c in df_identity.columns]
df_final = df_identity[final_cols_existing].copy()

print("Final dataframe shape:", df_final.shape)
print("\nRemaining missing values:")
print(df_final.isnull().sum()[df_final.isnull().sum() > 0])

df_final.head()

Final dataframe shape: (19117, 9)

Remaining missing values:
Series([], dtype: int64)

,userName,sourceIPAddress,eventSource,eventName,readOnly,errorCode,type,sessionContext.attributes.mfaAuthenticated,is_anomaly
0,benjamin,AWS Internal,s3.amazonaws.com,GetStorageLensConfiguration,True,NoError,IAMUser,true,0
1,benjamin,10.248.16.43,s3.amazonaws.com,GetBucketPublicAccessBlock,True,NoError,IAMUser,true,0
2,benjamin,10.248.16.43,s3.amazonaws.com,GetBucketPolicyStatus,True,NoError,IAMUser,true,0
3,benjamin,10.248.16.43,s3.amazonaws.com,GetBucketAcl,True,NoError,IAMUser,true,0
4,benjamin,10.248.16.43,s3.amazonaws.com,GetBucketPublicAccessBlock,True,NoSuchPublicAccessBlockConfiguration,IAMUser,true,0

In [19]:
df_final.isnull().sum()

userName                                      0
sourceIPAddress                               0
eventSource                                   0
eventName                                     0
readOnly                                      0
errorCode                                     0
type                                          0
sessionContext.attributes.mfaAuthenticated    0
is_anomaly                                    0
dtype: int64

In [ ]:
# Save the cleaned dataframe for the next stage (Graph Construction)
output_path = os.path.expanduser("~/Downloads/federated-hgnn-anomaly-detection/Dataset/Processed/df_identity_clean.csv")
df_final.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print("Data preparation complete. Ready for graph construction.")

Saved to: C:\Users\mikhael/Downloads/Pre Thesis/Dataset/Processed/df_identity_clean.csv
Data preparation complete. Ready for graph construction.